### PR TITLE
Support additional options as part of the Config

### PR DESCRIPTION
**Pull request by benjolitz**
This commit adds the ability to add a closure suitable for adding
additional options. It is expected to allow someone to set global,
module or class level variables so they can pass changes/options
suitable for making decisions.

Solves #129 

I've tried multiple names (additional_options, additional_opts_func, on, ...) and the only one that seems unambiguous is `on_options`.

I wonder if Kemal::Config is a good place to put it. I've noticed that other pieces for configuration land there and it seems strange to land option configuration in Kemal::CLI when the rest of the application options are stuffed into Kemal::Config.

Thoughts?

### CODE REVIEW

**Comment by sdogruyol** [comment]
@benjolitz how about renaming this to `extra_options`?

**Comment by f** [comment]
This makes sense. But agree with @sdogruyol renaming it into `extra_options`. `on_options` sounds strange alone.

**Comment by asterite** [comment]
In case you'll one day want to merge this, it's better to have this on the config:

```crystal
def extra_options(&@extra_options : OptionParser ->)
end
```

So on the client side it can be like this:

```crystal
config.extra_options do |parser|
  parser.on(...)
end
```

That way that fun literal with the explicit type is not needed.

And instead of using a `nil?` check I'd do:

```crystal
@config.extra_options.try &.call(opts)
```

**Comment by sdogruyol** [comment]
Merging. Thanks @benjolitz 👍 Also thanks @asterite for nice tips.

**Pull request merged**
