### PR TITLE
added mime types

### PR DESCRIPTION
**Pull request by crisward**
Added some mime type for images. Very new to crystal so hopefully this is ok.
Without this they default to octet, which just does a download

### CODE REVIEW

**Comment by sdogruyol** [comment]
Actually this comes from https://github.com/crystal-lang/crystal/blob/master/src/http/server/handlers/static_file_handler.cr#L77-L85.

IMHO this can be a PR to Crystal itself. WDYT?

**Comment by crisward** [comment]
I'll give it a go... Just thought that Kemal may have been quicker as I can install from master and don't have to wait for the next release on homebrew.

**Comment by sdogruyol** [comment]
I'll add this for now 👍 Thanks.

**Comment by Sija** [comment]
There's also https://github.com/pablotron/libmagic-crystal :)

**Comment by crisward** [comment]
Cool thanks...

**Pull request merged**
