### PR TITLE
Filters

### PR DESCRIPTION
**Pull request by werner**
Filters callback, similar to sinatra: http://www.sinatrarb.com/intro.html#Filters

### CODE REVIEW

**Comment by sdogruyol** [comment]
Thanks @werner. This looks cool :+1: 

For now i'm putting this on hold because unlike Sinatra we have easy to use `middleware`s which makes this kind of redundant.

**Comment by f** [comment]
It fails when there's no filters available.

And you are using `@tree` radix tree to push filters, but it's filled by `Router` payloads. And when router find that payload tries to cast `Filter` to `Router`.

```
process_filter(HTTP::Server::Context, Symbol)'

    process_filter(context, :before)
    ^~~~~~~~~~~~~~

in ./libs/kemal/kemal/handler.cr:38: can't cast Kemal::Route to Kemal::Filter

      filter = lookup.payload as Filter
```

**Comment by werner** [comment]
@f I just fixed the bug, thanks.

@sdogruyol should I try to implement this as a middleware?, thanks.

**Comment by sdogruyol** [comment]
@werner i think we can achieve the same behaviour with middlewares that's why we shouldn't make this built-in. Also having this reduces the overall performance since always have to check for `before` and `after` filters.

**Comment by werner** [comment]
@sdogruyol you're right, so I decided to create a kemal middleware as a shard: https://github.com/werner/kemal-filters.

Best regards :)

**Comment by sdogruyol** [comment]
@werner this looks great! Great job there :+1:

**Pull request closed without merging**
