### PR TITLE
Allow multiple values for a single parameter key.

### PR DESCRIPTION
**Pull request by MGerrior**
First pass at fixing #156. As @mperham said, it's a pretty typical approach for checkboxes, and is nice to have support for. I ran into a slight issue with `HTTP::Request.override_method` which was expecting `params["_method"]` to always be a string, not `Array(String)`. I opted to just choose the last method provided by the request.

Pretty new to crystal-lang and the Kemal project, so let me know if there is a different approach I should take.

### CODE REVIEW

**Comment by mperham** [comment]
I would simplify the API to always return Array(String). Otherwise caller has to make type checks all the time.

**Comment by sdogruyol** [comment]
@mperham then how would we handle single value parameter key?

**Comment by mperham** [comment]
.first?

**Comment by sdogruyol** [comment]
I think i prefer it this way than `.first?`.

@mperham could you provide an example of the caller checking for the type explicitly?

**Comment by MGerrior** [comment]
Switching to .first? would make this a breaking change for current
applications, right? I was going to avoid that, but maybe not possible with
change in type. I do think .first? is a little inconvenient since its not
likely to be the primary use case, with only the occasional use of multiple
values for things like check boxes.

I wanted an interface similar to Sinatra/Rails where the params would
return a String for a single value and an array for multiple values, but
not sure that's as easy in Crystal.
On Jun 12, 2016 1:04 PM, "Serdar Dogruyol" <notifications@github.com> wrote:

I think i prefer it this way than .first?.

@mperham <https://github.com/mperham> could you provide an example of the
caller checking for the type explicitly?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/sdogruyol/kemal/pull/161#issuecomment-225448232>, or mute
the thread
<https://github.com/notifications/unsubscribe/AAMbOKsziROhkBgC0vz3EWFtYW4VflABks5qLDwWgaJpZM4IzpBi>
.

**Comment by sdogruyol** [comment]
@MGerrior i agree on your point. My only worry is that how would this affect the performance of `ParamParser`

**Comment by mperham** [comment]
I'm thinking that anywhere the caller wants to handle a parameter that could have multiple values, they need to do this:

```ruby
x = params.url["foo"]
if x.is_a?(Array)
  # handle multiple
else
  # handle single
end
```

Yes?  Or am I misunderstanding?  If the API always returns Arrays, you only have a single pattern:

```ruby
x = params.url["foo"]
x.each do |value|
  # handle single
end
```

OTOH I get that single value is the common case.  Perhaps we could have a helper methods which guarantee a single value or multiple values and let the caller determine which one to call?

```ruby
x = params.url.values_for("foo") # always returns Array(String)
x.each do |value|
  # handle single
end
x = params.url.value_for("bar") # returns String
```

That would work for me and not break backwards compat.

**Comment by MGerrior** [comment]
I like the last approach @mperham. The way I see it, there are two
different ways to implement that. Either calls to params.query can return a
sort of ParamsCollection wrapper that responds to those values_for and
value_for methods. That or we wrap each individual parameter as a sort of
HTTP::Parameter that always responds to things like
params.query["foo"].values with an Array(String) and
params.query["foo"].value with a String (always the last value provided by
the user).

I'm leaning towards the latter, but I'll mess around with both hopefully
later tonight. And I'll try to get some benchmarks of the parser before and
after @sdogruyol.


On Jun 12, 2016 4:47 PM, "Mike Perham" <notifications@github.com> wrote:
>
> I'm thinking that anywhere the caller wants to handle a parameter that
could have multiple values, they need to do this:
>
> x = params.url["foo"]
> if x.is_a?(Array)
>   # handle multiple
> else
>   # handle single
> end
>
> Yes? Or am I misunderstanding? If the API always returns Arrays, you only
have a single pattern:
>
> x = params.url["foo"]
> x.each do |value|
>   # handle single
> end
>
> OTOH I get that single value is the common case. Perhaps we could have a
helper methods which guarantee a single value or multiple values and let
the caller determine which one to call?

**Comment by MGerrior** [comment]
In hindsight, @sdogruyol is there any reason we're not just using the built-in `HTTP::Params` class provided by [crystal](http://crystal-lang.org/api/HTTP/Params.html#parse%28query%3AString%29%3Aself-class-method) for this behavior? It seems like it solves all the use cases, since something like `params.query["foo"]` always returns a `String` (the first one in the input) and then you have access to `params.query.fetch_all("foo")` that always returns `Array(String)`. This seems like we might as well use the built in class instead of parsing the parameters and then storing them in a Hash.

**Comment by sdogruyol** [comment]
I want the `params` to be easily accessible as possible. 

@MGerrior Do you suggest that we should let the people parse `params` by their own?

P.S: As a bonus `radix` parses the `url` params when the route matches.

**Comment by MGerrior** [comment]
Sorry for the confusion, I didn't mean to imply that users should have to parse params on their own. I added a new commit to the PR [here](https://github.com/sdogruyol/kemal/pull/161/commits/d1f9c4394b18e0e0b27332a6beff333f596e33de) to illustrate what I mean.

The built-in `HTTP::Params` class in Crystal seems to provide the exact behavior that we want, and maintains the same interface for backwards compatibility, assuming applications weren't written to rely on  the params being a hash and we just using accessor functions like `[]`.

We could also wrap the `url` parameters in the `HTTP::Params` class for consistency, though it gets a little weirder with the JSON parsing I think since it supports types other than just `String` and `Array(String)`.

This new approach allows things like `params.query["foo"]` for single values and `params.query.fetch_all("foo")` for multiple value access.

**Comment by sdogruyol** [comment]
This is pretty self explanatory and clean to use. Thanks @MGerrior 👍

**Pull request merged**
