### PR TITLE
Decodes url parameters

### PR DESCRIPTION
**Pull request by samueleaton**
I found a little url parameter issue. In some other comparable non-crystal web frameworks, url parameters are decoded.

Here is an example comparing the response of ruby's sinatra with kemal.

### Sinatra  
```ruby
# GET [HOST]/user/sam%2Btest%40gmail.com

get "/user/:email" do
  params["email"]
end

# Response body => sam+test@gmail.com
```

### Kemal  
```ruby
# GET [HOST]/user/sam%2Btest%40gmail.com

get "/user/:email" do |env|
  env.params.url["email"]
end

# Response body => sam%2Btest%40gmail.com
```

Sinatra correctly decodes the url parameters. I have not used Sinatra in production, but I have a good amount of experience with the Node.js Express framework and I know that the url parameters are also decoded with Express.

Keep up the good work! 👍

### CODE REVIEW

**Comment by sdogruyol** [comment]
Yeah, i wasn't aware of this. Thanks @samueleaton 👍 💯

**Comment by sdogruyol** [comment]
Could you please add a spec for this exact scenario?

**Comment by samueleaton** [comment]
Added spec. All specs passed.

**Comment by sdogruyol** [comment]
LGTM 👍

**Pull request merged**
