### PR TITLE
Implement radix algorithm for routing (using Beryl)

### PR DESCRIPTION
**Pull request by f**
Radix algorithm makes the route search faster (about **~6x**).

**Radix Tree search on 200 routes (to find the last route):**
```
Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.54ms  767.82us   8.36ms   88.07%
    Req/Sec     1.97k   261.30     3.98k    97.51%
  39501 requests in 10.10s, 3.39MB read
```

**`.each` based lookup search on 200 routes (to find the last route)**
```
Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    15.60ms    4.43ms  32.48ms   88.84%
    Req/Sec   321.82      7.86   333.00     55.00%
  6424 requests in 10.03s, 564.61KB read
```

When searching in lower number of routes, radix search and loop based search are almost same.

### CODE REVIEW

**Comment by waterlink** [comment]
Looks awesome! :+1:

BTW, @luislavena Maybe it would make sense to extract Radix tree implementation to the library of its own? WDYT?

**Comment by f** [comment]
@waterlink @luislavena Yes! We need to decouple it as a pure tree implementation. I don't need Beryl at all, and to protect the maintainability, I do not want to seperate Beryl's tree implementation.

It would be awesome to have a radix-tree search library to use.

WDYT @sdogruyol?

**Comment by luislavena** [comment]
@f excellent work and excellent suggestion @waterlink 

I believe the only thing that is very *specific* inside the Radix implementation is the collecting of parameters, but code should be pretty easy to extract and dedup.

If you don't mind, will tackle that extraction this weekend and ping you here to update the references to that library instead of Beryl.

**Comment by sdogruyol** [comment]
@f this is great! Thanks a lot :100:

**Comment by luislavena** [comment]
@sdogruyol I thought would have been better to wait for the extracted library than make Kemal depend on Beryl.

But once the Radix is refactored outside, you can change it here.

Cheers.

**Comment by sdogruyol** [comment]
@luislavena i'm also waiting on that to make a new release :+1: For now it's ok for this to be on master.

**Pull request merged**
