### PR TITLE
Implement basic in-memory session store

### PR DESCRIPTION
**Pull request by mperham**
Sessions are stored in a non-persistent Hash.  Only String values are allowed.  A reaper fiber regularly removes any sessions which expire due to inactivity.

See also #91.

### CODE REVIEW

**Comment by sdogruyol** [comment]
This is great 👍 Thanks @mperham. 

Before merging how about adding a `secret_key` for configuration?

**Comment by f** [comment]
Wow. It's a feature that I'd wear my **fez** when it's merged 🤘

**Comment by mperham** [comment]
There's no encryption so there's no need for secrets.

**Comment by sdogruyol** [comment]
I see, that makes sense. Let's get this merged then :+1 Thanks again.

**Pull request merged**
