### PR TITLE
Extra information on Multi-Part FormData

### PR DESCRIPTION
**Pull request by miguelm**
Hi @sdogruyol ,

First let me thank you for your work on Kemal!

I was on a hackaton last weekend and used Crystal/Kemal, but one of the hurdles i was trying to tackle was multi part file upload onto my server, thankfully a PR about multipart was merged a few days before the hackaton that solved half my problem.

Nevertheless i found that not all info from the file was yielded:
- [your code ](https://github.com/sdogruyol/kemal/blob/master/src/kemal/helpers/helpers.cr#L94)
- [RX14 code](https://github.com/RX14/multipart.cr/blob/master/src/http/formdata.cr#L43)

Inside his code was metadata like the filename that i direly needed to accomplish what i set out to do. Hence i forked your repo and expanded the yielded parameters to the ones RX14 provides.

Feel free to discard this or accept.
If there's any changes that you deem necessary let me know

Thanks

### CODE REVIEW

**Comment by miguelm** [comment]
This will allow the following:

```ruby
parse_multipart(env) do |field, data, meta, headers|
  if field == "file"
    media_file = data.gets_to_end
    File.write("./tmp/#{meta.filename}", media_file)
  end
  puts "Upload complete"
end
```

We can now get the filename or other others

**Comment by sdogruyol** [comment]
Thanks for the PR. This is definitely an improvement to current Multipart handling.

I'd like to have this info but not necessarily force it into everyone. I think we can overload the method or find some other elegant way.

**Comment by sdogruyol** [comment]
So i thought of something like this

```crystal
def parse_multipart(env)
  HTTP::FormData.parse(env.request) do |field, data, meta, headers|
    yield Upload.new field, data, meta, headers
  end
end
```

On parsing

```crystal
post "/" do |env|
  parse_multipart(env) do |f|
    pp f.field
    pp f.data
    pp f.meta
    pp f.headers
  end
end
```

//cc @f

**Comment by miguelm** [comment]
if you want you can close this one :)

**Comment by sdogruyol** [comment]
Closed via https://github.com/sdogruyol/kemal/pull/224. Thanks 👍

**Comment by sdogruyol** [comment]
Meanwhile i just published https://github.com/sdogruyol/kemal/releases/tag/v0.16.1

**Comment by miguelm** [comment]
thanks :)

**Pull request closed without merging**
