### PR TITLE
Add API documentation generated by crystal doc

### PR DESCRIPTION
**Pull request by hugoabonizio**
As suggested by #209, this PR adds:

* API documentation generated by ```crystal doc```
* Rakefile with task ```rake docs``` that rebuilds the doc/ folder
* The link to docs on navbar.

### CODE REVIEW

**Comment by alex-lairan** [comment]
Good idea ! :+1: 

Could you remove White lines? They are so many with this tool (a simple sed or regex needed)

**Comment by sdogruyol** [comment]
@hugoabonizio thanks for the PR.

I've just published the docs to Crystal Docs https://crystal-docs.org/sdogruyol/kemal/

I think that's a better and centralized way of sharing Crystal doc.

**Comment by hugoabonizio** [comment]
@alex-lairan I think this could be a enhancement directly on ```crystal doc``` tool!

@sdogruyol You're right, I forgot about Crystal Docs! But it seems that there's no link to this right now, should we add one to the navbar?

**Comment by sdogruyol** [comment]
@hugoabonizio sure, i'll add a link to Crystal Docs 👍

**Pull request closed without merging**
