### PR TITLE
Fix block variable

### PR DESCRIPTION
**Pull request by mauricioabreu**

### CODE REVIEW

**Comment by sdogruyol** [comment]
Thank you

**Comment by mauricioabreu** [comment]
You are welcome! Thanks for the project. I am currently building a todo-backend version for: http://todobackend.com/

**Comment by sdogruyol** [comment]
That's great! Can't wait to see it 😍

**Comment by mauricioabreu** [comment]
@sdogruyol still missing the PATCH method.

https://github.com/mauricioabreu/todo-backend-kemal

**Pull request merged**
