### PR TITLE
Shorten the `before` and `after` syntax

### PR DESCRIPTION
**Pull request by jeromegn**
by removing `before_all`, `after_all` and using `"all"` as a default verb.

I believe that's a bit less awkward and what people come to expect.

It's also compatible with the old syntax.

### CODE REVIEW

**Comment by jmoriau** [comment]
I made explicitly this way because `before_all` was more explicit than simply `before` see #96

**Comment by jmoriau** [comment]
Also have you tried it ?  Because this change only removes the `before_all` and `after_all` it doesn't add `before` and `after`.

**Comment by jeromegn** [comment]
@jmoriau yea I noticed that. My bad, this PR is not ready at all in its current state.

I initially thought the specs were testing the macro, but they aren't. I will fix that.

I also realize this might not make much sense unless kemal can handle an arbitrary number of filters for the same routes. Right now it raises if there is more than one filter for the same verb and path combination, but maybe it should be able to store as many as necessary and run them in order when the request comes in.

*/me ponders*

**Comment by jmoriau** [comment]
Also what would be the point of calling multiple time `before_x` on the same route ?

**Comment by jeromegn** [comment]
@jmoriau the point is that code can be organized in a more flexible manner when we can have more than one before, after filter on endpoints.

People could load add-ons shards (like something that would handle sessions) that would do stuff like that for them automatically.

```crystal
# app.cr
require "./kemal/session"

before_all do |env|
  # do something with env
  raise "Unauthorized" unless authorized?(env)
end

def authorized?(env)
  env.session["username"] == env.params["username"]
end

get "/:username/private_stuff" do |env|
end
```

```crystal
# kemal/session.cr

before_all do |env|
  # given there was some mechanism to store data in a Kemal::Context
  env.session = Session.new(env.cookies)
end
```

Then both routes would have the filters run before them in the order they were defined.

My thinking is inspired by Sinatra.

**Comment by jmoriau** [comment]
3rd party addons shouldn't use `before_x` or `after_x` but instead do all their work in their own middleware.

`before_x` or `after_x` should only be used by end user to add a block before one/many calls imho.

**Comment by jeromegn** [comment]
Maybe not third party, example is probably wrong hehe! But just for sake of code organization.

Anyway, this is all a bit off-topic. I fired this PR a bit too quickly too!

**Comment by jmoriau** [comment]
Sorry I was just curious about the use case :smile:

**Comment by jeromegn** [comment]
@jmoriau no problem :smile:, I liked it.

**Pull request closed without merging**
