### PR TITLE
Add only_routes and exclude routes to HTTP::Handler

### PR DESCRIPTION
**Pull request by sdogruyol**
Original work of @samueleaton continued.

### CODE REVIEW

**Comment by sdogruyol** [comment]
Meanwhile this really impacts the performance if used in a middleware.

```crystal
require "kemal"

logging false

get "/" do |env|
  env.response.content_type = "text/plain"
  "hello world"
end

class TestHandler < HTTP::Handler
  def call(env)
    only_routes env, ["/somebody", "/someone", "/something", "/admins", "/users", "/"]
    call_next env
  end
end

add_handler TestHandler.new

Kemal.run
```

With `only_routes`


```
➜  ~ wrk -c 40 -d 20 http://localhost:3000
Running 20s test @ http://localhost:3000
  2 threads and 40 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   730.26us  155.99us   5.43ms   90.66%
    Req/Sec    27.54k   819.61    28.44k    86.07%
  1101338 requests in 20.10s, 127.09MB read
Requests/sec:  54791.98
Transfer/sec:      6.32MB
```

Without `only_routes`

```
➜  ~ wrk -c 40 -d 20 http://localhost:3000
Running 20s test @ http://localhost:3000
  2 threads and 40 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   425.15us  120.21us   2.82ms   75.59%
    Req/Sec    47.16k     1.81k   48.97k    90.55%
  1886674 requests in 20.10s, 217.71MB read
Requests/sec:  93864.37
Transfer/sec:     10.83MB
```

//cc @samueleaton

**Comment by samueleaton** [comment]
Hmm... We should see if there is a way to add a middleware directly to a route instead. It would probably increase performance.

Example  
```ruby
class FirstHandler < HTTP::Handler
  def call(env)
    puts "running first middleware..."
    call_next env
  end
end

class SecondHandler < HTTP::Handler
  def call(env)
    puts "running second middleware..."
    call_next env
  end
end

get "/", middleware: [ FirstHandler.new, SecondHandler.new ] do |env|
  env.response.content_type = "text/plain"
  "hello world"
end
```

This way if you wanted a stack of middlewares that authenticated a user it would be easy to apply it to multiple routes:

```ruby
class VerifyAuthHeaders < HTTP::Handler
  def call(env)
    puts "This would verify that auth headers exist"
    call_next env
  end
end

class VerifyUserInfo < HTTP::Handler
  def call(env)
    puts "This would verify that the given user info is valid"
    call_next env
  end
end

verify_user_middlewares = [VerifyAuthHeaders.new, VerifyUserInfo.new]

get "/", middleware: verify_user_middlewares do |env|
  env.response.content_type = "text/plain"
  "hello world"
end

get "/secure/path", middleware: verify_user_middlewares do |env|
  env.response.content_type = "text/plain"
  "hello world"
end

# does not use middlewares
get "/insecure/path" do |env|
  env.response.content_type = "text/plain"
  "hello world"
end
```

**Comment by sdogruyol** [comment]
@samueleaton i'm working on an alternative implementation for this.

**Comment by samueleaton** [comment]
should close this in favor of #245?

**Comment by sdogruyol** [comment]
Closed in favor of https://github.com/sdogruyol/kemal/pull/245

**Pull request closed without merging**
