### PR TITLE
Updating json sample

### PR DESCRIPTION
**Pull request by stephan-nordnes-eriksen**
There is a new syntax for this now. You need to write env.response.content_type

### CODE REVIEW

**Comment by sdogruyol** [comment]
Ouch! That's right :+1: Thanks a lot :smiley:

**Comment by stephan-nordnes-eriksen** [comment]
While on the subject. I find the documentation on the webpage a bit lacking :( For instance: how to do auth? You mention basic_auth, but not how to use it. Any chance there will be some updates there?

**Comment by sdogruyol** [comment]
You are absolutely right! Documentation definitely needs to be improved :+1:

**Comment by stephan-nordnes-eriksen** [comment]
Awesome :)

**Pull request merged**
