### PR TITLE
Add only_routes and exclude_routes macros for middlewares

### PR DESCRIPTION
**Pull request by samueleaton**
I wasn't seeing a way to tell middleware to run (or not to run) conditionally based on the path.

I propose to add `only_routes` and `exclude_routes` that can run _anywhere_ in the middleware (but preferably at the top) to conditionally exit the middleware or to continue.

Examples:

```ruby
# only_routes macro
class MyCustomHandler < HTTP::Handler
  def call(context)
    only_routes context, ["/admin/**", "/user"]
    # if the request path DOES NOT match one of given paths in the previous line then none
    # of the rest of the middleware will be ran

    puts "Doing some custom stuff here"
    call_next context
  end
end

# exclude_routes macro
class MyCustomHandler < HTTP::Handler
  def call(context)
    exclude_routes context, ["/", "/about"]
    # if the request path DOES match one of given paths in the previous line then none
    # of the rest of the middleware will be ran
    
    puts "Doing some custom stuff here"
    call_next context
  end
end
```

### CODE REVIEW

**Comment by sdogruyol** [comment]
//cc @askn @f WDYT?

**Comment by sdogruyol** [comment]
@samueleaton can we have specs for this?

**Comment by f** [comment]
Since it's affecting middlewares I think it has to have specs.

Besides, this seems very edge use case to me. May be a external plugin but not in the core system IMHO.

**Comment by f** [comment]
Additionally, it uses regex to check routes which we switched to radix search b/c of performance issues.

If the user use these macros the performance will be significantly bad since every route will be checked if the middleware should run or not.

The only concerns I have is these :)

But it's a good idea to cover some cases. Nice work, btw @samueleaton 👍

**Comment by sdogruyol** [comment]
I agree with @f. This is a good but a bit edge case. It should be a Kemal plugin of its' own.

**Comment by samueleaton** [comment]
I ran some benchmarks and its not what I expected.
I just wanted to hit a very barebones route to see if adding `only_routes` affected speed.

The route:
```ruby
get "/" do |env|
  env.response.content_type = "text/plain"
  "hello world"
end
```

My test handler:

```ruby
class TestHandler < HTTP::Handler
  def call(ctx)
    # only_routes ctx, ["/", "/admins", "/users"]
    call_next ctx
  end
end
```

I tested twice with and without the `only_routes ...` line commented out.

I just used the example numbers on the `wrk` page, `wrk -t12 -c400 -d30s http://127.0.0.1:4444`.

## Results

Twice *WITH* `only_routes`:

```
Running 30s test @ http://127.0.0.1:4444
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   110.53ms  289.61ms   2.00s    89.47%
    Req/Sec     1.52k   743.63     7.70k    73.85%
  537890 requests in 30.05s, 62.07MB read
  Socket errors: connect 0, read 247, write 0, timeout 1097
Requests/sec:  17897.39
Transfer/sec:      2.07MB
--------------------------------------------------------
Running 30s test @ http://127.0.0.1:4444
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    85.94ms  257.59ms   2.00s    91.52%
    Req/Sec     1.52k   658.61     7.30k    74.54%
  529711 requests in 30.06s, 61.13MB read
  Socket errors: connect 0, read 208, write 0, timeout 1199
Requests/sec:  17623.61
Transfer/sec:      2.03MB
```

Twice *WITHOUT* `only_routes` (commented out):

```
Running 30s test @ http://127.0.0.1:4444
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    94.55ms  263.25ms   2.00s    90.69%
    Req/Sec     1.47k   726.64     6.73k    76.49%
  504617 requests in 30.08s, 58.23MB read
  Socket errors: connect 0, read 227, write 0, timeout 1247
Requests/sec:  16774.17
Transfer/sec:      1.94MB
--------------------------------------------------------
Running 30s test @ http://127.0.0.1:4444
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   125.90ms  300.24ms   2.00s    88.41%
    Req/Sec     1.44k   775.17     6.45k    73.77%
  505088 requests in 30.06s, 58.28MB read
  Socket errors: connect 0, read 233, write 0, timeout 1223
Requests/sec:  16801.60
Transfer/sec:      1.94MB
```

How could this be?

*tested on 2015 MacBook Pro 2.7GHZ i5, 16GB ram*

**Comment by sdogruyol** [comment]
@samueleaton t12 means use 12 threads which is not suitable for a Macbook. Also ***please turn off** logging via

```crystal
logging false
```

And rerun with

```
wrk -c100 -d30s http://127.0.0.1:4444
```

**Comment by samueleaton** [comment]
😝 Duh. Sorry, I had just gotten out of bed and didn't take time to use my brain yet. 

The app I was testing against had *lots* of routes and a pooling connection to a DB going on, so I just started a blank app from scratch to run these new benchmarks.

Twice *WITH* `only_routes`:
```
Running 30s test @ http://127.0.0.1:4444
  2 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.09ms  337.65us   9.19ms   73.16%
    Req/Sec    23.87k     1.82k   64.35k    96.17%
  1427168 requests in 30.10s, 164.69MB read
Requests/sec:  47412.69
Transfer/sec:      5.47MB
--------------------------------------------------------
Running 30s test @ http://127.0.0.1:4444
  2 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.08ms  288.17us   8.48ms   72.64%
    Req/Sec    24.09k   708.51    25.89k    69.60%
  1442916 requests in 30.10s, 166.50MB read
Requests/sec:  47934.44
Transfer/sec:      5.53MB
```

Twice *WITH* `only_routes` (commented out):

```
Running 30s test @ http://127.0.0.1:4444
  2 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.10ms    0.86ms  41.44ms   99.03%
    Req/Sec    24.03k     0.93k   28.49k    87.33%
  1434304 requests in 30.00s, 165.51MB read
Requests/sec:  47806.50
Transfer/sec:      5.52MB
--------------------------------------------------------
Running 30s test @ http://127.0.0.1:4444
  2 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.09ms  281.00us  10.05ms   71.91%
    Req/Sec    23.90k   519.73    26.35k    79.57%
  1431184 requests in 30.10s, 165.15MB read
Requests/sec:  47545.27
Transfer/sec:      5.49MB
```

Seems pretty negligible to me.

**Comment by samueleaton** [comment]
😝 Duh. Sorry, I had just gotten out of bed and didn't take time to use my brain yet. 

The app I was testing against had *lots* of routes and a pooling connection to a DB going on, so I just started a blank app from scratch to run these new benchmarks.

Twice *WITH* `only_routes`:
```
Running 30s test @ http://127.0.0.1:4444
  2 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.17ms  295.49us   8.72ms   73.10%
    Req/Sec    23.04k   840.73    27.19k    78.41%
  1380096 requests in 30.10s, 159.26MB read
Requests/sec:  45847.98
Transfer/sec:      5.29MB
--------------------------------------------------------
Running 30s test @ http://127.0.0.1:4444
  2 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.18ms  357.49us  15.15ms   76.71%
    Req/Sec    22.97k     1.32k   29.23k    83.50%
  1371542 requests in 30.00s, 158.27MB read
Requests/sec:  45714.21
Transfer/sec:      5.28MB
```

Twice *WITHOUT* `only_routes` (commented out):

```
Running 30s test @ http://127.0.0.1:4444
  2 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.10ms    0.86ms  41.44ms   99.03%
    Req/Sec    24.03k     0.93k   28.49k    87.33%
  1434304 requests in 30.00s, 165.51MB read
Requests/sec:  47806.50
Transfer/sec:      5.52MB
--------------------------------------------------------
Running 30s test @ http://127.0.0.1:4444
  2 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.09ms  281.00us  10.05ms   71.91%
    Req/Sec    23.90k   519.73    26.35k    79.57%
  1431184 requests in 30.10s, 165.15MB read
Requests/sec:  47545.27
Transfer/sec:      5.49MB
```

**Comment by samueleaton** [comment]
@f I've been doing mostly Node.js for the last couple of years and got accustomed to being able to define which routes use specific middlewares. This didn't seem like an edge case where I'm coming from. 
If there is a different paradigm then I might need to just adjust my style.

**Comment by samueleaton** [comment]
If I were to add the ability to pass an array of routes to filters, that would also fill this need. 

example: 

```ruby
before_get ["/foo/*", "/bar"]  do |env|
  # do something
end
```

**Comment by sdogruyol** [comment]
@samueleaton can you please reopen this (i can't). I think this really makes sense with a middleware oriented architecture.

**Comment by samueleaton** [comment]
@sdogruyol Sorry I was on vacation for 4 days. Is everything good?

**Comment by sdogruyol** [comment]
Reopened as https://github.com/sdogruyol/kemal/pull/244

**Pull request closed without merging**
