### PR TITLE
Replace implementation with more appropriate URI.unescape

### PR DESCRIPTION
**Pull request by samueleaton**
Sorry for the quick fix after recently merging the other PR. I was reading through the API docs and discovered a more appropriate method for decoding URL params. 

I ran the specs and everything works as expected. Sorry 😓

### CODE REVIEW

**Comment by alex-lairan** [comment]
What is the advantage than the previous way? :)

If the both do the job with the same accuracy, I don't think this is necessary because this add a new require. More you have require, more the code compiled is bigger. ;)

**Comment by sdogruyol** [comment]
@alex-lairan `uri` is already included.

**Comment by sdogruyol** [comment]
Thanks @samueleaton 👍

**Comment by alex-lairan** [comment]
Oh ok !

I have my c++ reference where you add for example 
```#include <array>```
This increase your *.o* size ^.^

**Comment by samueleaton** [comment]
@alex-lairan 
>Once a file is required, the compiler remembers its absolute path and later requires of that same file will be ignored.

From [the docs](https://crystal-lang.org/docs/syntax_and_semantics/requiring_files.html)

**Pull request merged**
