### PR TITLE
Middleware ordering

### PR DESCRIPTION
**Pull request by sdogruyol**
This improves middleware ordering.

Middlewares should work as intended, before all before_* filters and routes.

```
Request -> Middleware -> Filter -> Route
```

This works but `crystal spec` fails with a weird issue.

```
crystal spec

F...........................................................................

Failures:

  1) Handler adds custom handler before before_*
     Failure/Error: client_response.body.should eq("Kemal is so Great")

       expected: "Kemal is so Great"
            got: "Kemal Great"

     # ./spec/handler_spec.cr:39
```

Meanwhile requiring the spec files with exact paths work.

```
crystal spec spec/handler_spec.cr spec/middleware/filters_spec.cr spec/middleware/csrf_spec.cr spec/middleware/http_basic_auth_spec.cr spec/common_exception_handler_spec.cr spec/common_log_handler_spec.cr spec/config_spec.cr spec/context_spec.cr spec/helpers_spec.cr spec/init_handler_spec.cr spec/param_parser_spec.cr spec/route_handler_spec.cr spec/route_spec.cr spec/session_spec.cr spec/static_file_handler.cr spec/view_spec.cr spec/websocket_handler_spec.cr

2016-10-27 17:33:59 +0300 200 GET / 76.0µs
..........................2016-10-27 17:33:59 +0300 200 GET / 12.0µs
.2016-10-27 17:33:59 +0300 200 GET / 10.0µs
.2016-10-27 17:33:59 +0300 200 GET / 26.0µs
................................................................

Finished in 13.8 milliseconds
92 examples, 0 failures, 0 errors, 0 pending
```
//cc @asterite

### CODE REVIEW

**Comment by asterite** [comment]
It fails for this file (I added an empty `it`):

```cr
require "./spec_helper"

it "renders 404 on route not found" do
end

class CustomTestHandler < HTTP::Handler
  def call(env)
    env.response << "Kemal"
    call_next env
  end
end

it "adds custom handler before before_*" do
  before_get "/" do |env|
    env.response << " is"
  end

  before_get "/" do |env|
    env.response << " so"
  end

  before_all "/" do
  end

  add_handler CustomTestHandler.new

  get "/" do |env|
    " Great"
  end
  request = HTTP::Request.new("GET", "/")
  client_response = call_request_on_app(request)
  client_response.status_code.should eq(200)
  client_response.body.should eq("Kemal is so Great")
end
```

I think it has to do with these lines in spec_helper.cr:

```cr
Spec.before_each do
  config = Kemal.config
  config.env = "development"
  config.setup
end

Spec.after_each do
  Kemal.config.clear
  Kemal::RouteHandler::INSTANCE.tree = Radix::Tree(Route).new
  Kemal::Middleware::Filter::INSTANCE.tree = Radix::Tree(Array(Kemal::Middleware::Block)).new
end
```

But I don't know all of kemal's code so I can't know why that is breaking things. Maybe it would be a good idea to remove all those constants and global state and try to test stuff in isolation. For example the global `get`/`post` macros could work on a global instance, but also allow a way to create a Kemal app without it being global and test that. Maybe it will be easier.

**Comment by sdogruyol** [comment]
@asterite thanks a lot for your insights 👍  It's definitely the fault of test suite and my bad specs 😢

**Comment by sdogruyol** [comment]
Specs are passing 🎉  Thanks @asterite 🇦🇷

**Comment by asterite** [comment]
@sdogruyol Cool! Glad I was able to help :-)

**Comment by f** [comment]
@sdogruyol @asterite You guys are awesome. I got "feyiz" from a simple issue. ("feyiz" means "enlightenment" in Turkish that Crystal community use too much when talking about Crystal)

**Pull request merged**
