### PR TITLE
Fixes for upcoming 0.18

### PR DESCRIPTION
**Pull request by noumar**
Fixes the recently moved SSL context for servers.

### CODE REVIEW

**Comment by noumar** [comment]
Travis fails on `latest` as the change is still only in Crystal `nightly`.

**Comment by noumar** [comment]
@sdogruyol, Travis fails on `latest` as the change is still only in Crystal `nightly`.

**Comment by sdogruyol** [comment]
Hey @noumar , thanks for the pull request.

Let's wait till this gets published in Crystal latest 👍

**Comment by sdogruyol** [comment]
Closing in favour of #162

**Pull request closed without merging**
